services:
  - type: web
    name: epubchat-bot
    runtime: python3
    buildCommand: pip install -r storage/requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DEEPL_API_KEY
        sync: false
      - key: TUMBLR_API_KEY
        sync: false
      - key: WATTPAD_API_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        fromSecret: log_level
      - key: ADMIN_IDS
        fromSecret: admin_ids
